class levelUpThisGame:
    def __init__(self, name, level):
        self.name = name
        self.level = level

    def level_up(self):
        self.level += 1
        print(f"{self.name} has leveled up to level {self.level}!")
player = levelUpThisGame("Hero", 1)
print(f"{player.name} is currently at level {player.level}.")
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()   
player.level_up()   
player.level_up()   
player.level_up()   
player.level_up()   
player.level_up()   
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()
player.level_up()